# Puerto de la aplicacion
server.port=8080

##
## MONGODB - FASE 2
##
spring.data.mongodb.uri=mongodb://localhost:27017/cardpurchases
spring.data.mongodb.database=cardpurchases

# Mostrar logs de MongoDB
logging.level.org.springframework.data.mongodb=DEBUG